version: '3.3'

networks:
  ntpgsql: 
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.22.0.0/24

services: 
  mongodb:
    build: 
      context: .
    restart: unless-stopped
    container_name: mongodb-gestione-user
    volumes: 
      - data-volume:/data/db
    networks:     
      ntpgsql: 
        ipv4_address: 172.22.0.2
    ports:
      - target: 27017
        published: 37018
        protocol: tcp
        mode: host

volumes: 
  data-volume:

